name: sweyer
description: Open source music player built with Flutter
homepage: https://github.com/nt4f04uNd/sweyer
repository: https://github.com/nt4f04uNd/sweyer
issue_tracker: https://github.com/nt4f04uNd/sweyer/issues
publish_to: none
version: 1.0.2+3
 
environment:
  sdk: ">=2.6.0<3.0.0"
  # Commit 183f0e797a3bf8aa1b35b650150f7522d5d10377
  # flutter: 1.24.0-8.0.pre.374

dependencies:
  # color_thief_flutter: ^1.0.2
  async: ^2.4.2
  animations: ^1.1.2
  fluttertoast: ^7.1.8
  permission_handler: ^5.1.0+2
  shared_preferences: 2.0.0 # don't use latest because of https://github.com/flutter/flutter/issues/77155
  path_provider: ^2.0.1
  json_annotation: ^3.1.1
  percent_indicator: ^2.1.9+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  package_info: ^0.4.3+4
  url_launcher: ^6.0.1
  flare_flutter: ^2.0.6
  auto_size_text: ^3.0.0-nullsafety.0
  marquee: ^1.7.0
  equatable: ^2.0.0-nullsafety.4
  device_info: ^1.0.0
  enum_to_string: ^1.0.14
  sqflite: ^1.3.2+2
  path: ^1.7.0
  flutter_sticky_header: ^0.5.0
  multiple_localization: ^0.2.0-nullsafety.0
  scrollable_positioned_list: ^0.1.9
  nt4f04unds_widgets:
    path: c:/dev/projects/native/nt4f04unds_widgets/
    # git:
    #   url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
    #   ref: 1.1.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  # intl_translation: ^0.17.10+1
  intl_translation:
    git:
      url: https://github.com/nt4f04uNd/intl_translation
      ref: 198ba30710a7aeba94813389dac47c9092d11e6c

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
    # don't include a whole folder here because of README  
   - assets/animations/play_pause.flr
   - assets/animations/checkmark.flr

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/manrope-extrabold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/manrope-bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/manrope-semibold.ttf
          weight: 600
